hotkeys:
  shell: {}
ssh: {}
terminal:
  colorScheme: &ref_0
    name: Argonaut
    foreground: '#d1d2d3'
    background: '#000000'
    cursor: '#ff0018'
    colors:
      - '#232323'
      - '#ff000f'
      - '#8ce10b'
      - '#ffb900'
      - '#008df8'
      - '#6d43a6'
      - '#00d8eb'
      - '#ffffff'
      - '#444444'
      - '#ff2740'
      - '#abe15b'
      - '#ffd242'
      - '#0092ff'
      - '#9a5feb'
      - '#67fff0'
      - '#ffffff'
  environment: {}
  shell: wsl-Ubuntu-18.04
  font: Powerline Consolas
  fontSize: 11
  background: theme
  autoOpen: true
  bracketedPaste: true
  ligatures: false
  customColorSchemes:
    - *ref_0
  frontend: xterm
  cursor: underline
appearance:
  theme: Compact
  vibrancy: false
  opacity: 1
  vibrancyType: fluent
pluginBlacklist:
  - ssh
