ssh: {}
hotkeys: {}
terminal:
  fontSize: 11
  shell: wsl-Ubuntu-18.04
  customShell: /usr/bin/zsh
  font: Powerline Consolas
  background: colorScheme
  cursor: block
  frontend: hterm
  colorScheme:
    name: Argonaut
    foreground: '#fffaf4'
    background: '#0e1019'
    cursor: '#ff0018'
    colors:
      - '#232323'
      - '#ff000f'
      - '#8ce10b'
      - '#ffb900'
      - '#008df8'
      - '#6d43a6'
      - '#00d8eb'
      - '#ffffff'
      - '#444444'
      - '#ff2740'
      - '#abe15b'
      - '#ffd242'
      - '#0092ff'
      - '#9a5feb'
      - '#67fff0'
      - '#ffffff'
  autoOpen: true
appearance:
  theme: Compact
  vibrancy: false
  frame: thin
  opacity: 0.95
enableAnalytics: false
