## https://github.com/jedisct1/dnscrypt-proxy/blob/master/dnscrypt-proxy/example-dnscrypt-proxy.toml
## https://github.com/jedisct1/dnscrypt-proxy/wiki/DNS-server-sources
## https://github.com/jedisct1/dnscrypt-proxy/wiki/Public-blacklists

server_names = ['cloudflare', 'google']
#server_names = ['2.ghs-secure-dns', '2.ghs-secure-dns.1']
listen_addresses = ['127.0.0.1:53']
max_clients = 250
ipv4_servers = true
ipv6_servers = false
dnscrypt_servers = true
doh_servers = true
require_dnssec = false
require_nolog = true
require_nofilter = true
force_tcp = false
timeout = 2500
keepalive = 30
lb_strategy = 'p2'
log_level = 0
log_file = 'dnscrypt-proxy.log'
cert_refresh_delay = 240
dnscrypt_ephemeral_keys = false
tls_disable_session_tickets = false
tls_cipher_suite = [52392, 49199]
fallback_resolver = '1.1.1.1:53'
ignore_system_dns = false
netprobe_timeout = 60
log_files_max_size = 10
log_files_max_age = 7
log_files_max_backups = 1
block_ipv6 = true

forwarding_rules = 'forwarding-rules.txt'
# cloaking_rules = 'cloaking-rules.txt'

cache = true
cache_size = 512
cache_min_ttl = 600
cache_max_ttl = 86400
cache_neg_min_ttl = 60
cache_neg_max_ttl = 600

[query_log]
  file = 'query.log'
  format = 'tsv'
  # ignored_qtypes = ['DNSKEY', 'NS']

[nx_log]
  file = 'nx.log'
  format = 'tsv'

[blacklist]
  # blacklist_file = 'blacklist.txt'
  # log_file = 'blocked.log'
  # log_format = 'tsv'

[ip_blacklist]
  # blacklist_file = 'ip-blacklist.txt'
  # log_file = 'ip-blocked.log'
  # log_format = 'tsv'

[whitelist]
  # whitelist_file = 'whitelist.txt'
  # log_file = 'whitelisted.log'
  # log_format = 'tsv'

[sources]
  [sources.'public-resolvers']
  urls = ['https://raw.githubusercontent.com/DNSCrypt/dnscrypt-resolvers/master/v2/public-resolvers.md', 'https://download.dnscrypt.info/resolvers-list/v2/public-resolvers.md']
  cache_file = 'public-resolvers.md'
  minisign_key = 'RWQf6LRCGA9i53mlYecO4IzT51TGPpvWucNSCh1CBM0QTaLn73Y7GFO3'
  refresh_delay = 72
  prefix = ''

  [sources.'opennic']
  urls = ['https://raw.githubusercontent.com/DNSCrypt/dnscrypt-resolvers/master/v2/opennic.md', 'https://download.dnscrypt.info/resolvers-list/v2/opennic.md']
  minisign_key = 'RWQf6LRCGA9i53mlYecO4IzT51TGPpvWucNSCh1CBM0QTaLn73Y7GFO3'
  cache_file = 'opennic.md'  
  
#[static]
#   [static.'2.ghs-secure-dns']
#   stamp = 'sdns://AQcAAAAAAAAAEjQxLjE4NS4xMjAuODA6ODQ0MyCwLkRO4gWFauZH1iwenQgk5GOZN7J_e9DleR0LoJX8bRAyLmdocy1zZWN1cmUtZG5z'
#   [static.'2.ghs-secure-dns.1']
#   stamp = 'sdns://AQcAAAAAAAAAEjQxLjE4NS4xMjAuOTA6ODQ0MyDDHrK6Lf1zyV6ECiDKXtLFc1trPVfR7uVOHXHLtqF_hxIyLmdocy1zZWN1cmUtZG5zLjE'
#  # [static.'cloudflare']
#  # stamp = 'sdns://AgcAAAAAAAAABzEuMC4wLjGgENk8mGSlIfMGXMOlIlCcKvq7AVgcrZxtjon911-ep0cg63Ul-I8NlFj4GplQGb_TTLiczclX57DvMV8Q-JdjgRgSZG5zLmNsb3VkZmxhcmUuY29tCi9kbnMtcXVlcnk'

